# Generated by Django 3.0.5 on 2020-04-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('codigo', models.CharField(max_length=60, unique=True, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('codigo', models.CharField(max_length=3, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=35, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoSUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo Procedimento')),
                ('nome', models.CharField(max_length=260, verbose_name='Codigo Procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Codigo Prestador')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome Prestador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escala.Empresa')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('data_producao', models.DateField(verbose_name='Data Produção')),
                ('data_pagamento', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porta', models.CharField(choices=[('PRONTO SOCORRO', 'PRONTO SOCORRO'), ('AMBULATORIO', 'AMBULATORIO'), ('INTERNACAO', 'INTERNACAO'), ('EXAMES', 'EXAMES')], max_length=20)),
                ('convenio', models.CharField(choices=[('SUS', 'SUS'), ('CONVENIO', 'CONVENIO')], max_length=10)),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_escala.Especialidade')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escala.Prestador')),
                ('procedimento_sus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_escala.ProcedimentoSUS')),
            ],
            options={
                'ordering': ['-modificacao'],
            },
        ),
    ]
