# Generated by Django 3.0.5 on 2020-05-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('codigo', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('nome', models.CharField(max_length=35, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='MultiEmpresa',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Multi Empresa',
                'verbose_name_plural': 'Multi Empresas',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoSUS',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=260, verbose_name='Codigo Procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome Prestador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escala.Empresa')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criacão')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação')),
                ('data_producao', models.DateField(verbose_name='Data Produção')),
                ('data_pagamento', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('porta', models.CharField(choices=[('PRONTO SOCORRO', 'PRONTO SOCORRO'), ('AMBULATORIO', 'AMBULATORIO'), ('INTERNACAO', 'INTERNACAO'), ('EXAMES', 'EXAMES'), ('ENFERMARIA', 'ENFERMARIA')], max_length=20)),
                ('convenio', models.CharField(choices=[('SUS', 'SUS'), ('CONVENIO', 'CONVENIO')], max_length=10)),
                ('escala', models.CharField(blank=True, choices=[('PERIODO', 'PERIODO'), ('PLANTAO', 'PLANTAO'), ('PERIODO-RES', 'PERIODO-RES'), ('HORAS', 'HORAS'), ('QUANTIDADE', 'QUANTIDADE')], default='', max_length=20, null=True, verbose_name='escala')),
                ('empresa_multi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escala.MultiEmpresa')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_escala.Especialidade')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escala.Prestador')),
                ('procedimento_sus', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_escala.ProcedimentoSUS')),
                ('servico_escala', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_escala.Servico')),
            ],
            options={
                'ordering': ['-modificacao'],
            },
        ),
    ]
