# Generated by Django 3.0.5 on 2020-04-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escala', '0002_auto_20200428_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='escala',
            field=models.CharField(blank=True, choices=[('PERIODO', 'PERIODO'), ('PLANTAO', 'PLANTAO'), ('PERIODO-RES', 'PERIODO-RES'), ('HORAS', 'HORAS'), ('QUANTIDADE', 'QUANTIDADE')], default='', max_length=20, null=True, verbose_name='escala'),
        ),
    ]
