# Generated by Django 3.0.5 on 2020-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escala', '0003_escala_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=35, unique=True, verbose_name='Codigo'),
        ),
    ]
