# Generated by Django 3.0.5 on 2020-05-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_escala', '0005_auto_20200429_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='procedimento_sus',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_escala.ProcedimentoSUS'),
        ),
    ]
